security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login:
                login_path: admin_login
                check_path: admin_login
                username_parameter: form[_username]
                password_parameter: form[_password]
            logout:
                path: /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/login, roles: PUBLIC_ACCESS }
