services:
  php:
    build:
      context: .
    networks:
      default:
        aliases:
          - php-fpm
    volumes:
      - build:/var/www/public/build
      - media:/var/www/public/media
      - /etc/localtime:/etc/localtime
    depends_on:
      - mariadb

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/var/www/media
      - build:/var/www/build
      - /etc/localtime:/etc/localtime
    ports:
     - 8080:80

volumes:
  build:
  media:
  mysql:
