framework:
  assets:
    json_manifest_path: '%kernel.public_dir%/build/manifest.json'

  default_locale: '%locale%'
  enabled_locales: '%app.locales%'
  #csrf_protection: true
  translator:
    default_path: '%kernel.project_dir%/user/translations'
    fallbacks:
      - 'en'

  router:
    strict_requirements: ~

  secret: '%env(APP_SECRET)%'
  #http_method_override: true

  # Enables session support
  session:
    handler_id: ~

  #esi: true
  #fragments: true
  php_errors:
    log: true

  cache:
    directory: '%kernel.project_dir%/cache'
#    pools:
#      unchained.cache:
#        adapter: cache.adapter.filesystem
#        tags: true
    #prefix_seed: your_vendor_name/app_name
    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu
  validation:
    email_validation_mode: html5
